name: test-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7
  - spacy==2.2.3
  - jupyterlab==1.2.6
  - sqlalchemy==1.3.13
  - pandas==1.0.1
  - pytest
  - pyyaml
  - memory_profiler
  - ipython

